//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yAuction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Listings()
        {
            this.listingBid = new HashSet<listingBid>();
        }
    
        public int Id { get; set; }
        public string description { get; set; }
        public byte[] image { get; set; }
        public double priceStart { get; set; }
        public Nullable<double> priceAuction { get; set; }
        public Nullable<double> priceBuy { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> accountId { get; set; }
    
        public virtual listing_Category listing_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listingBid> listingBid { get; set; }
        public virtual Users Users { get; set; }
    }
}
